parameters:
  timezone: 'Asia/Novosibirsk'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Skeleton\Common\:
    resource: '../src/'
    exclude:
      - '../src/Component/ModuleSystem/'
      - '../src/Exception/'
      - '../src/Kernel.php'
      - '../src/Module/'

  Skeleton\Common\Application\Component\CommandBus\CommandBusComponentInterface:
    class: Skeleton\Common\Infrastructure\Component\CommandBus\CommandBusComponent
    arguments:
      $handlersLocator: '@command.bus.messenger.handlers_locator'

  Skeleton\Common\Application\Component\QueryBus\QueryBusComponentInterface:
    class: Skeleton\Common\Infrastructure\Component\QueryBus\QueryBusComponent
    arguments:
      $handlersLocator: '@query.bus.messenger.handlers_locator'

  Skeleton\Common\Component\Event\EventBusInterface:
    class: Skeleton\Common\Infrastructure\Component\Event\SymfonyMessengerEventBus
    arguments:
      $eventBus: '@event.bus'

  Skeleton\Common\Component\Clock\Clock:
    arguments:
      $timezone: '%timezone%'

  Psr\Clock\ClockInterface:
    alias: Skeleton\Common\Component\Clock\Clock
